// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://umdunkjeupasnmtnvdhs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVtZHVua2pldXBhc25tdG52ZGhzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyMzc1MjksImV4cCI6MjA2NTgxMzUyOX0.ZUsCu7UV6v0fMoyc2xVjg36s-IhErg4vB1Sb0--UMU4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});